(()=>{
const SB=window.supabase.createClient("https://khzqerdrhzdrkhdxfaxn.supabase.co","sb_publishable_0LIpUqxt0wjVxlmjOswCkQ_EHk3ZmDq");
const fields=[
["Home","Hero title",".hero-content h1","home","hero_title"],["Home","Hero subtitle",".hero-content h2","home","hero_subtitle"],
["Services","Heading","#services .section-heading h2","services","heading"],["Pricing","Heading","#pricing .section-heading h2","pricing","heading"],
["Contact","Heading","#contact h2","contact","heading"]
];
async function apply(){const {data}=await SB.from("site_content").select("*");(data||[]).forEach(r=>{const f=fields.find(x=>x[3]===r.section&&x[4]===r.content_key);if(f){const e=document.querySelector(f[2]);if(e)e.textContent=r.content_value}})}
function shell(){const d=document.createElement("div");d.innerHTML='<button class="cms-launch" id="cmsLaunch">⚙ Admin</button><div class="cms-overlay" id="cms"><div class="cms-card"><header><div><b>Jalali Tech</b><small>Website Admin</small></div><button id="cmsX">×</button></header><div id="cmsBody"></div></div></div>';document.body.append(...d.children);document.getElementById("cmsLaunch").onclick=login;document.getElementById("cmsX").onclick=()=>document.getElementById("cms").classList.remove("open")}
async function login(){document.getElementById("cms").classList.add("open");const {data:{session}}=await SB.auth.getSession();session?dashboard():loginView()}
function loginView(){const b=document.getElementById("cmsBody");b.innerHTML='<div class="cms-login"><h2>Admin Login</h2><p>Sign in to manage your live website.</p><input id="cmsEmail" type="email" placeholder="Email"><input id="cmsPass" type="password" placeholder="Password"><button id="cmsLogin">Sign in</button><small id="cmsMsg">Use the admin account you create in Supabase Authentication.</small></div>';document.getElementById("cmsLogin").onclick=async()=>{const {error}=await SB.auth.signInWithPassword({email:cmsEmail.value,password:cmsPass.value});cmsMsg.textContent=error?error.message:"Signed in";if(!error)dashboard()}}
async function dashboard(){const {data}=await SB.from("site_content").select("*");const b=document.getElementById("cmsBody");b.innerHTML='<div class="cms-dashboard"><nav><b>Dashboard</b><span>Home</span><span>Services</span><span>Pricing</span><span>Contact</span><span>AI Assistant</span><span>Settings</span></nav><main><div class="cms-title"><div><h2>Website Content</h2><p>Edit your website and publish changes for everyone.</p></div><button id="cmsLogout">Log out</button></div><div id="cmsFields" class="cms-grid"></div><button id="cmsPublish" class="cms-publish">Publish changes</button><p id="cmsStatus"></p></main></div>';const g=document.getElementById("cmsFields");fields.forEach(f=>{const r=(data||[]).find(x=>x.section===f[3]&&x.content_key===f[4]);const c=document.createElement("label");c.className="cms-field";c.innerHTML='<span>'+f[0]+' · '+f[1]+'</span><textarea></textarea>';c.querySelector("textarea").value=r?.content_value||document.querySelector(f[2])?.textContent.trim()||"";c.querySelector("textarea").dataset.section=f[3];c.querySelector("textarea").dataset.key=f[4];g.appendChild(c)});cmsLogout.onclick=async()=>{await SB.auth.signOut();loginView()};cmsPublish.onclick=publish}
async function publish(){const rows=[...document.querySelectorAll(".cms-field textarea")].map(x=>({section:x.dataset.section,content_key:x.dataset.key,content_value:x.value,updated_at:new Date().toISOString()}));const {error}=await SB.from("site_content").upsert(rows,{onConflict:"section,content_key"});cmsStatus.textContent=error?error.message:"Published successfully ✓";if(!error)apply()}
document.addEventListener("DOMContentLoaded",async()=>{apply();const {data:{session}}=await SB.auth.getSession();if(session)shell();});
})();